

CREATE DATABASE BillingDb ;

GO

USE BillingDb;

GO

CREATE TABLE Customers(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
[Name] NVARCHAR(200) NOT NULL,
Phone NVARCHAR(14) NOT NULL,
[Address] NVARCHAR(MAX)
)

GO

CREATE TABLE Products(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
Code NVARCHAR(100) NOT NULL UNIQUE,
[Name] NVARCHAR(200) NOT NULL,
Rate float NOT NULL
)

GO

CREATE TABLE Inventories(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
[Date] DATETIME NOT NULL,
BillNo NVARCHAR(200) UNIQUE,
CustomerId INT NOT NULL REFERENCES Customers(Id),
TotalDiscount float NOT NULL,
TotalBillAmount float NOT NULL,
DueAmount float NOT NULL,
PaidAmount float NOT NULL
)

GO

CREATE TABLE InventoryProducts(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
InventoryId INT NOT NULL REFERENCES Inventories(Id),
ProductId INT NOT NULL REFERENCES Products(Id),
Rate float NOT NULL,
Qty float NOT NULL,
Discount float NOT NULL
)